---
kind: pipeline
type: kubernetes
name: build-ssh

metadata:
  namespace: drone

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry.sud0.com
    insecure: true
    repo: registry.sud0.com/ssh
    tags: latest
    dockerfile: ssh/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: kubernetes
name: build-sslh

metadata:
  namespace: drone

steps:
- name: kaniko
  image: plugins/kaniko
  settings:
    registry: registry.sud0.com
    insecure: true
    repo: registry.sud0.com/sslh
    tags: latest
    dockerfile: sslh/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
