---
kind: pipeline
type: kubernetes
name: build-ssh

metadata:
  namespace: drone

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    registry: registry.home.sud0.com
    repo: ssh
    tags: latest
    dockerfile: ssh/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

---
kind: pipeline
type: kubernetes
name: build-sslh

metadata:
  namespace: drone

steps:
- name: kaniko
  image: banzaicloud/drone-kaniko
  settings:
    registry: registry.home.sud0.com
    repo: sslh
    tags: latest
    dockerfile: sslh/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
